baseURL = "https://schwertshild-test.netlify.app/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Schwertshild Security System"
[markup.goldmark.renderer]
unsafe = true
