author = "Andre Bonne"
contact_form_action = "#"
description = "SchwertShild Security System"
logo = "/images/logomakr-8hqpyc.png"
logo_width = "200px"
[navigation_button]
enable = true
label = "Get Early Bord Access"
link = "contact"
[preloader]
enable = true
preloader = "/images/logomakr-8hqpyc.png"
[[social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
